// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Utils;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.AlternativeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alternative1");

                    b.Property<string>("alternative2");

                    b.Property<string>("alternative3");

                    b.Property<string>("alternative4");

                    b.Property<string>("alternative5");

                    b.HasKey("id");

                    b.ToTable("AlternativeModel");
                });

            modelBuilder.Entity("WebAPI.Models.CourseModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<int>("schoolId");

                    b.Property<int>("subjectId");

                    b.HasKey("id");

                    b.HasIndex("schoolId");

                    b.HasIndex("subjectId");

                    b.ToTable("CourseModel");
                });

            modelBuilder.Entity("WebAPI.Models.QuestionModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TestModelid");

                    b.Property<int>("alternativeId");

                    b.Property<string>("dificulty");

                    b.Property<string>("imgUrl");

                    b.Property<string>("topic");

                    b.HasKey("id");

                    b.HasIndex("TestModelid");

                    b.HasIndex("alternativeId");

                    b.ToTable("QuestionModel");
                });

            modelBuilder.Entity("WebAPI.Models.SchoolModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("SchoolModel");
                });

            modelBuilder.Entity("WebAPI.Models.SubjectModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("UserModelcpf");

                    b.Property<int>("courseId");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("UserModelcpf");

                    b.ToTable("SubjectModel");
                });

            modelBuilder.Entity("WebAPI.Models.TestModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dueDate");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("TestModel");
                });

            modelBuilder.Entity("WebAPI.Models.UserModel", b =>
                {
                    b.Property<long>("cpf")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<bool>("isActive");

                    b.Property<bool>("isAdmin");

                    b.Property<string>("name");

                    b.Property<string>("phone");

                    b.HasKey("cpf");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("WebAPI.Models.CourseModel", b =>
                {
                    b.HasOne("WebAPI.Models.SchoolModel", "School")
                        .WithMany()
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebAPI.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebAPI.Models.QuestionModel", b =>
                {
                    b.HasOne("WebAPI.Models.TestModel")
                        .WithMany("Questions")
                        .HasForeignKey("TestModelid");

                    b.HasOne("WebAPI.Models.AlternativeModel", "Alternative")
                        .WithMany()
                        .HasForeignKey("alternativeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebAPI.Models.SubjectModel", b =>
                {
                    b.HasOne("WebAPI.Models.UserModel")
                        .WithMany("Subjects")
                        .HasForeignKey("UserModelcpf");
                });
#pragma warning restore 612, 618
        }
    }
}
